
[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  base = "master"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

